@startuml
skinparam style strictuml
skinparam linetype polyline
skinparam PackagePadding 10
hide empty members

package Application {
    package "Structure SDK" as StructureSDK #EEEEEE{
        () Structure
        () StructureSLAM 
    }

    package "OpenGL ES" as OpenGL #EEEEEE{
        [CAEAGLLayer]
        () gl_UtilsFunction
    }

    node "Structure Sensor Scanner" as StructureSensorScanner #C8E6C9{
        [ViewController]
        node "Scanning View" {
            [CameraController] --> [ScannerViewController]
            [SLAMController] --> [ScannerViewController]
            [SensorController] --> [ScannerViewController]
            [OpenGLController] --> [ScannerViewController]
            node "MeshView" {
                [MeshRenderer] --> [MeshViewController]
            }
        } 
    }

    node "AR Interface" as ARInterface #BBDEFB{
        node "Model Editor View" as ModelEditorView {
            [ModelEditorViewController] 
        }

        node "Model Selection View" as ModelSelectionView #BBDEFB{
        }

        [ModelEditorViewController] --> [ViewController]
    }

    package ARKit #EEEEEE{
        () ARSCNViewDelegate
    }

    package SceneKit #EEEEEE{
        () SCNSceneRender --> () SCNScene
        SCNScene --> () SCNNode
    }

    package AVKit #EEEEEE{
        () AVCaptureDevice
    }

    package ModelIO #EEEEEE{
        () MDLAsset
    }
}



[SLAMController] --> StructureSLAM
[SensorController] --> Structure
[ScannerViewController] --> [CAEAGLLayer]
[OpenGLController] ..> gl_UtilsFunction : use
[ScannerViewController] --> [ViewController]
[MeshViewController] --> [ScannerViewController]
[MeshViewController] --> StructureSLAM
[CameraController] --> AVCaptureDevice
SCNSceneRender --> ARSCNViewDelegate
[ModelEditorViewController] --> ARSCNViewDelegate
[MeshRenderer] --> OpenGLController
MDLAsset --> SCNNode
StructureSLAM --> MDLAsset

legend
    |= |= Type |
    |<#EEEEEE>     | Unchange |
    |<#C8E6C9>     | Adapted |
    |<#BBDEFB>     | Added |
endlegend

@enduml

