@startuml
skinparam style strictuml
title Structure SDK Interface Class diagram

package Structure {
class STColorFrame {
    width : int
    hegiht : int
    shiftData : uint16_T
    depthInMillimeters : float
    halfResolutionDepthFrame : STDepthFrame
    timestamp : NSTimeInterval
    glProjectionMatrix : GLKMatrix4
    applyExpensiveCorrection : bool
    STDepthFrame : registeredToColorFrame(colorFrame : STColorFrame)
    void : colorCameraPoseInDepthCoordinateFrame(matrix4x4: float)
}

interface STDepthFrame {

}
}

STDepthFrame <|-down- STColorFrame

@enduml
